### PR TITLE
Arjun baseline

### PR DESCRIPTION
**Pull request by ArjunPrihar**
The long-anticipated baseline removal code is complete. Please take a look and share your comments.

### CODE REVIEW

**Comment by AnitaZhang0526** [comment]
This would be a method under the FTIR class, right? I will be writing that either tonight or tomorrow afternoon, so just want to make sure.

**Comment by AnitaZhang0526** [comment]
But the code looks good. Thanks Arjun!

**Comment by ArjunPrihar** [comment]
> This would be a method under the FTIR class, right? I will be writing that either tonight or tomorrow afternoon, so just want to make sure.

Yeah! I dont know where the correct spot is to put the 'import numpy' stuff so i left it as a comment but we can move it. Same with the bottom commented-out 'main' stuff, that I just left there for myself when I was testing but can remove.

**Comment by asrobang1** [comment]
When I ran pytest, I got the following error from baseline_test.py

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Tests\baseline_test.py:14: ValueError
```

**Comment by ArjunPrihar** [comment]
> When I ran pytest, I got the following error from baseline_test.py
> 
> ```
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> 
> Tests\baseline_test.py:14: ValueError
> ```

Yeah, I ran into this issue as well but after I had already started the pull request. I am still trying to figure out why my test file isnt working, but the actual code should be fine.

**Comment by ArjunPrihar** [comment]
aborted this one in place of the arjun-baseline-2 branch since there were issues with being so egregiously behind develop

**Pull request closed without merging**
