### PR TITLE
first configuration for auto-documentation

### PR DESCRIPTION
**Pull request by AnitaZhang0526**
first version of the configuration file for auto-documentation

### CODE REVIEW

**Comment by JordanHamel** [comment]
How do I test this? Is there a way for me to build the documentation on my computer?

**Comment by pirolster** [comment]
I need to look back at the lecture notes to understand what conf.py is even supposed to do and I will circle back

**Comment by pirolster** [comment]
@JordanHamel this link might be helpful! I think it would be valuable for us to review as a group what comments need to look like across our source files in order for the auto-documentation to work

**Comment by JordanHamel** [comment]
@pirolster agree!

@AnitaZhang0526 I was hoping you could add instructions to the readme for this!

**Pull request merged**
